resolver: lts-18.0

# stack unpack HDBC-postgresql
extra-deps:
  - HDBC-postgresql-2.5.0.0

packages:
  - .
  - ./pqexample

nix:
  enable: true
  packages:
#    - postgresql # segfault
#    - postgresql_12 # segfault
    - postgresql_13 # segfault