resolver: lts-18.0

# extra-deps:
  # - HDBC-postgresql-2.5.0.0

packages:
  - .
  - ./pqexample

nix:
  enable: true
  packages:
#    - postgresql # No segfault
#    - postgresql_12 # No segfault
    - postgresql_13 # No segfault